# Generated by Django 2.1.5 on 2019-04-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='アイテム名')),
                ('is_set', models.BooleanField(default=False, verbose_name='セット装備')),
                ('set_name', models.CharField(default='', max_length=128, verbose_name='セット名')),
            ],
        ),
        migrations.CreateModel(
            name='Large_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OW', 'One-Weapons'), ('AM', 'Armors'), ('TW', 'Two-Weapons'), ('AC', 'Accessories')], default='Armors', max_length=20, verbose_name='大分類')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='アイテム配置場所')),
            ],
        ),
        migrations.CreateModel(
            name='Small_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Helm', 'Helm'), ('Shoulders', 'Shoulders'), ('Armor', 'Armor'), ('Pants', 'Pants'), ('Gloves', 'Gloves'), ('Boots', 'Boots'), ('Belt', 'Belt'), ('Ring', 'Ring'), ('Amulet', 'Amulet'), ('Medal', 'Medal'), ('One-gun', 'One-gun'), ('Two-gun', 'Two-gun'), ('One-sword', 'One-sword'), ('Two-sword', 'Two-sword'), ('One-mace', 'One-mace'), ('Two-mace', 'Two-mace'), ('One-ax', 'One-ax'), ('Two-ax', 'Two-ax'), ('One-scepter', 'One-scepter'), ('One-dagger', 'One-dagger'), ('Shield', 'Shield'), ('Off-hand', 'Off-hand')], default='Helm', max_length=20, verbose_name='小分類')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_large_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_stash.Large_class'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_stash.Place'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_small_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_stash.Small_class'),
        ),
    ]
