# Generated by Django 2.1.5 on 2019-04-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_stash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='small_class',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_stash.Large_class'),
        ),
    ]
