# Generated by Django 2.1.5 on 2019-04-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_stash', '0002_small_class_parent_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='set_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='セット名'),
        ),
    ]
