# Generated by Django 2.1.5 on 2019-04-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_stash', '0003_auto_20190405_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='セット名')),
                ('is_myth', models.BooleanField(default=True, verbose_name='神話級')),
                ('contained_parts', models.CharField(default='', max_length=128, verbose_name='含まれる部位')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='belonged_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parts', to='my_stash.Itemset'),
        ),
    ]
